apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: laravel-gitops
  region: us-east-1
  version: "1.29"

managedNodeGroups:
  - name: ng-prod
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: false

