apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: prod
type: Opaque
stringData:
  DB_DATABASE: laravel
  DB_PASSWORD: CHANGE_ME
  DB_USERNAME: laravel
  MYSQL_DATABASE: laravel
  MYSQL_PASSWORD: CHANGE_ME
  MYSQL_ROOT_PASSWORD: CHANGE_ROOT
  MYSQL_USER: laravel
