apiVersion: batch/v1
kind: CronJob
metadata:
  name: laravel-scheduler
  namespace: prod
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: scheduler
              image: laravel-app-image:v3
              command: ["sh", "-c"]
              args: ["php artisan schedule:run"]
              envFrom:
                - configMapRef:
                    name: laravel-config
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-secret
                      key: DB_PASSWORD
              resources:
                requests:
                  cpu: "50m"
                  memory: "64Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"

